#######################################################
# 
# Asignatura.py
# Python implementation of the Class Asignatura
# Generated by Enterprise Architect
# Created on:      07-sep.-2016 11:29:32 p. m.
# Original author: Gerardo Mares
# 
#######################################################
import GeneradorSecuencia

class Asignatura:
    __bloque = 0
    __gestorSecuencia = GeneradorSecuencia()
    __nombreAsignatura = " "
    __semestre = 0
    def getAsignatura():
        pass

    def getBloque():
        pass

    def getSemestre():
        pass

    def listarAsignaturas():
        pass

    def listarBloques():
        pass

    def listarSemestres():
        pass

    def setAsignatura(asignatura):
        pass

    def setBloque(bloque):
        pass

    def setSemestre(semestre):
        pass