#######################################################
#
# Asignatura.py
# Python implementation of the Class Asignatura
# Generated by Enterprise Architect
# Created on:      07-sep.-2016 11:29:32 p. m.
# Original author: Gerardo Mares
#
#######################################################
from DAO.GestorFichero import GestorFichero

class Asignatura:
    bloque = 0
    gestorFichero = GestorFichero()
    nombreAsignatura = " "
    semestre = 0
    def getAsignatura(self):
        return self.nombreAsignatura

    def getBloque(self):
        return bloque

    def getSemestre(self):
        return semestre

    def listarAsignaturas(self):
        global gestorFichero
        gestorFichero = GestorFichero()
        listaDeAsignaturas = []
        try:
            listaDeAsignaturas = gestorFichero.getAsignaturas()
        except Exception as e:
            listaDeAsignaturas.append("No hay asignaturas que mostrar :/")
        return listaDeAsignaturas

    def listarBloques(self):
        global gestorFichero
        gestorFichero = GestorFichero()
        listaDeBloques = []
        try:
            listaDeBloques = gestorFichero.getBloquesAsignatura(nombreAsignatura, semestre)
        except Exception as e:
            listaDeBloques.append("Debes seleccionar una asignatura antes")
        return listaDeBloques

    def listarSemestres(self):
        global gestorFichero
        gestorFichero = GestorFichero()
        listaDeSemestres = []
        try:
            listaDeSemestres = gestorFichero.getSemestresAsignatura(nombreAsignatura)
        except Exception as e:
            listaDeSemestres.append("Debes seleccionar una asignatura antes")
        return listaDeSemestres

    def setAsignatura(self, miAsignatura):
        resultadoAsignacion = 0
        if miAsignatura:
            if miAsignatura.isdigit():
                resultadoAsignacion = 0
            else:
                self.nombreAsignatura = miAsignatura
                resultadoAsignacion = 1
        else:
            resultadoAsignacion = 0
        return resultadoAsignacion

    def setBloque(self, miBloque):
        resultadoAsignacion = 0
        if miBloque:
            if len(miBloque) > 1:
                resultadoAsignacion = 0
            else:
                if miBloque.isdigit():
                    global bloque
                    bloque = miBloque + ".csv"
                    resultadoAsignacion = 1
                else:
                    resultadoAsignacion = 0
        else:
            resultadoAsignacion = 0
        return resultadoAsignacion

    def setSemestre(self, miSemestre):
        resultadoAsignacion = 0
        if miSemestre:
            if len(miSemestre) > 1:
                resultadoAsignacion = 0
            else:
                if miSemestre.isdigit():
                    global semestre
                    semestre = miSemestre
                    resultadoAsignacion = 1
                else:
                    resultadoAsignacion = 0
        else:
            resultadoAsignacion = 0
        return resultadoAsignacion
