#######################################################
#
# Asignatura.py
# Python implementation of the Class Asignatura
# Generated by Enterprise Architect
# Created on:      07-sep.-2016 11:29:32 p. m.
# Original author: Gerardo Mares
#
#######################################################
from DAO.GestorFichero import GestorFichero

class Asignatura:
    bloque = 0
    gestorFichero = GestorFichero()
    nombreAsignatura = " "
    semestre = 0
    def getAsignatura():
        return nombreAsignatura

    def getBloque():
        return bloque

    def getSemestre():
        return semestre

    def listarAsignaturas():
        try:
            listaDeAsignaturas = gestorFichero.getAsignaturas()
        except Exception as e:
            listaDeAsignaturas = ("No hay asignaturas que mostrar :/")
        return listaDeAsignaturas

    def listarBloques():
        try:
            listaDeBloques = gestorFichero.getBloquesAsignatura(nombreAsignatura, semestre)
        except Exception as e:
            listaDeBloques = ("Debes seleccionar una asignatura antes")
        return listaDeBloques

    def listarSemestres():
        try:
            listaDeSemestres = gestorFichero.getSemestresAsignatura(nombreAsignatura)
        except Exception as e:
            listaDeSemestres = ("Debes seleccionar una asignatura antes")
        return listaDeSemestres

    def setAsignatura(self, miAsignatura):
        resultadoAsignacion = 0
        if miAsignatura:
            if miAsignatura.isdigit():
                resultadoAsignacion = 0
            else:
                nombreAsignatura = miAsignatura
                resultadoAsignacion = 1
        else:
            resultadoAsignacion = 0
        return resultadoAsignacion

    def setBloque(self, miBloque):
        resultadoAsignacion = 0
        if miBloque:
            if len(miBloque) > 1:
                resultadoAsignacion = 0
            else:
                if miBloque.isdigit():
                    bloque = miBloque
                    resultadoAsignacion = 1
                else:
                    resultadoAsignacion = 0
        else:
            resultadoAsignacion = 0
        return resultadoAsignacion

    def setSemestre(self, miSemestre):
        resultadoAsignacion = 0
        if miSemestre:
            if len(miSemestre) > 1:
                resultadoAsignacion = 0
            else:
                if miSemestre.isdigit():
                    semestre = miSemestre
                    resultadoAsignacion = 1
                else:
                    resultadoAsignacion = 0
        else:
            resultadoAsignacion = 0
        return resultadoAsignacion
