#######################################################
# 
# ContenidosFijos.py
# Python implementation of the Class ContenidosFijos
# Generated by Enterprise Architect
# Created on:      07-sep.-2016 11:29:32 p. m.
# Original author: DARKENSES
# 
#######################################################
from Dominio.ContenidosEspecificos import ContenidosEspecificos
from Dominio.ContenidosGenerales import ContenidosGenerales
from Fachada.Asignatura import Asignatura

class ContenidosFijos:
    m_ContenidosGenerales= ContenidosGenerales()

    m_ContenidosEspecificos= ContenidosEspecificos()

    def getContenidosEspecificos():
        pass

    def getContenidosGenerales():
        pass

    def listarContenidosEspecificos(asignatura):
        pass

    def listarContenidosGenerales(asignatura):
        pass

    def setCompetenciasCierre(disciplinaresElegidas, genericasElegidas):
        pass

    def setCompetenciasDesarrollo(disciplinaresElegidas, genericasElegidas):
        pass

    def setCompetenciasInicio(disciplinaresElegidas, genericasElegidas):
        pass

    def setContenidosEspecificos(actitudinalesElegidos, declarativosElegidos, procedimentalesElegidos):
        pass

    def setEvidenciasCierre(evidenciasElegidas):
        pass

    def setEvidenciasDesarrollo(evidenciasElegidas):
        pass

    def setEvidenciasInicio(evidenciasElegidas):
        pass

    def setInstrumentosCierre(instrumentosElegidos):
        pass

    def setInstrumentosDesarrollo(instrumentosElegidos):
        pass

    def setInstrumentosInicio(instrumentosElegidos):
        pass