#######################################################
# 
# ContenidosGenerales.py
# Python implementation of the Class ContenidosGenerales
# Generated by Enterprise Architect
# Created on:      07-sep.-2016 11:09:42 p. m.
# Original author: Gerardo Mares
# 
#######################################################


class ContenidosGenerales:
    """Lo que compartirán todas las materias
    """
    __generadorSecuencia = GeneradorSecuencia()
    def getContenidosGenerales():
        pass

    def __listarContenidosGenerales(asignatura, bloques, semestre):
        pass

    def setCompetencias(disciplinaresElegidas, genericasElegidas):
        pass

    def setEvidencias(evidencias):
        pass

    def setInstrumentos(instrumentos):
        pass