#######################################################
#
# ContenidosGenerales.py
# Python implementation of the Class ContenidosGenerales
# Generated by Enterprise Architect
# Created on:      07-sep.-2016 11:29:26 p. m.
# Original author: Gerardo Mares
#
#######################################################
import GestorFichero

class ContenidosGenerales:
    """Lo que compartir�n todas las materias
    """
    gestorFichero = GestorFichero()
    def getContenidosGenerales():
        pass

    def __listarContenidosGenerales(asignatura, bloques, semestre):
        pass

    def setCompetencias(disciplinaresElegidas, genericasElegidas):
        pass

    def setEvidencias(evidencias):
        pass

    def setInstrumentos(instrumentos):
        pass
