#######################################################
# 
# ContenidosAgregadosGenerales.py
# Python implementation of the Class ContenidosAgregadosGenerales
# Generated by Enterprise Architect
# Created on:      07-sep.-2016 11:09:42 p. m.
# Original author: Gerardo Mares
# 
#######################################################


class ContenidosAgregadosGenerales:
    __aprendizaje = " "
    __Ensenianza = " "