#######################################################
# 
# ContenidosEspecificos.py
# Python implementation of the Class ContenidosEspecificos
# Generated by Enterprise Architect
# Created on:      07-sep.-2016 11:09:42 p. m.
# Original author: DARKENSES
# 
#######################################################


class ContenidosEspecificos:
    __generadorSecuencia = GeneradorSecuencia()
    def getContenidosEspecificos():
        pass

    def __listarContenidosEspecificos(asignatura, bloques, semestre):
        pass

    def setContenidosEspecificos(actitudinalesElegidos, declarativosElegidos, prodecimentalesElegidos):
        pass