#######################################################
# 
# ContenidosAgregadosInformativos.py
# Python implementation of the Class ContenidosAgregadosInformativos
# Generated by Enterprise Architect
# Created on:      07-sep.-2016 11:09:42 p. m.
# Original author: DARKENSES
# 
#######################################################


class ContenidosAgregadosInformativos:
    """Contenido que el usuario agregará a mano en la interfaz de la aplicación y se
    usará al generar la secuencia
    """
    __asignaturasRelacionadas = " "
    __fuentesInformacion = " "
    __observaciones = " "
    __propositoSecuencia = " "
    __recursosMateriales = " "