#######################################################
#
# GestorFichero.py
# Python implementation of the Class GestorFichero
# Generated by Enterprise Architect
# Created on:      07-sep.-2016 11:29:18 p. m.
# Original author: Luis Fernando Gomez Alejandre
#
#######################################################
import csv
import glob
import os
from os import listdir



class GestorFichero:
    def getAsignaturas(self):
        listaDeAsignaturas = []
        try:
            pathCarpetas = ".\\DAO\\Archivos\\Asignaturas"
            for archivo in listdir( pathCarpetas ):
                listaDeAsignaturas.append(archivo)
        except Exception as e:
            listaDeAsignaturas.append("No hay asignaturas disponibles")
        return listaDeAsignaturas

    def getBloquesAsignatura(self, nombreAsignatura, semestreAsignatura):
        listaDeBloques = []
        try:
            pathArchivo = ".\\DAO\\Archivos\\Asignaturas\\" + nombreAsignatura + "\\" + semestreAsignatura + ".csv"
            archivo = glob.glob(pathArchivo)
            archivoAbierto = csv.reader(open(archivo[0], 'r'), delimiter=';')
            for fila,columna in enumerate(archivoAbierto):
                listaDeBloques.append(columna[0][0:8])
        except Exception as e:
            listaDeBloques.append("No hay bloques disponibles")
        return listaDeBloques

    def getContenidosEspecificos(asignatura):
        return 0

    def getContenidosGenerales(asignatura):
        return 0

    def getSemestresAsignatura(self, nombreAsignatura):
        listaDeSemestres = []
        try:
            pathCarpetas = ".\\DAO\\Archivos\\Asignaturas\\" + nombreAsignatura
            for archivo in listdir( pathCarpetas ):
                listaDeSemestres.append(archivo)
        except Exception as e:
            listaDeSemestres.append("No hay semestres disponibles")
        return listaDeSemestres
