#######################################################
# 
# GestorFichero.py
# Python implementation of the Class GestorFichero
# Generated by Enterprise Architect
# Created on:      07-sep.-2016 11:29:18 p. m.
# Original author: Luis Fernando Gomez Alejandre
# 
#######################################################
from Fachada.Asignatura import Asignatura

class GestorFichero:
    def getAsignaturas():
        pass

    def getBloquesAsignatura(nombreAsignatura, semestreAsignatura):
        pass

    def getContenidosEspecificos(asignatura):
        pass

    def getContenidosGenerales(asignatura):
        pass

    def getSemestresAsignatura(nombreAsignatura):
        pass